refactor conditionals and add enable config properties
Valensas/header-propagation pull request #2
Opened 2024-09-11 11:41 UTC by yavuzselimkaraman

@moray95 @cantaylancapraz

2024-09-11 17:01 UTC, moray95 approved these changes

2024-09-12 07:04 UTC, taylancapraz requested changes

2024-09-12 07:04 UTC, taylancapraz commented on README.md
> +spring:
Sanki doküman ve kod uyuşmuyor, burada spring olmamalı

2024-09-12 07:06 UTC, taylancapraz approved these changes

2024-09-12 07:17 UTC, yavuzselimkaraman commented on README.md
> +spring:
düzelttim

2024-09-12 07:19 UTC, merged